on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'

    - run: npm init -y --scope ${{ github.repository_owner }}

    - run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        npm version 1.0.0-g${{ github.sha }}

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_PACKAGES }}

    - run: npm unpublish "@${{ github.repository }}@1.0.0-g${{ github.sha }}"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_PACKAGES }}
